# Project information
site_name: DutyCalls

# Copyright
copyright: 'Copyright &copy; 2021 Transceptor Technology'

# Configuration
theme:
  name: material
  custom_dir: theme
  favicon: images/favicon.ico
  logo: images/logo-white.png
  # palette:
  #   primary: white
  #   accent: red

nav:
- Introduction: index.md
- Getting started: getting-started.md
- Alerts: alerts.md
- Expectations: expectations.md
- Actions: actions.md
- Integrations: integrations.md
- Tags: tags.md
- REST API: rest-api.md
- Email: email.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - def_list