site_name: DutyCalls
theme:
  name: material
  favicon: 'images/favicon.ico'
  logo: 'images/icon-black.png'
  palette:
    primary: 'white'
    accent: 'red'
nav:
- Introduction: 'index.md'
- Getting started: 'getting-started.md'
- REST API: 'rest-api.md'